package de.woerteler.charty;

import de.woerteler.charty.ChartParser.Edge;
import de.woerteler.latex.LaTeXDisplay;

/**
 * Class representing a parse tree generated by the {@link ChartParser}.
 * 
 * @author Leo Woerteler
 */
public final class ParseTree {

  /** Root edge of this tree. */
  private final Edge edge;

  /**
   * Constructor.
   * 
   * @param e root edge
   */
  ParseTree(final Edge e) {
    edge = e;
  }

  /**
   * Get the displayer of this parse tree.
   * 
   * @param method The method to draw the syntax tree.
   * @return parse tree displayer
   * @throws Exception if the conversion fails
   */
  public Displayer getDisplayer(final DisplayMethod method)
      throws Exception {
    return method.getDisplayer(edge);
  }

  /**
   * Getter.
   * 
   * @return Creates a LaTeX representation of the syntax tree.
   */
  public String getLaTeXText() {
    return LaTeXDisplay.toLaTeX(edge);
  }

}
