package de.woerteler.charty;

import java.awt.image.BufferedImage;
import java.io.IOException;

import de.woerteler.charty.ChartParser.Edge;
import de.woerteler.latex.LaTeX;

/**
 * Class representing a parse tree generated by the {@link ChartParser}.
 * 
 * @author Leo Woerteler
 */
public final class ParseTree {

	/** Root edge of this tree. */
	private final Edge edge;
	/** The image. */
	private BufferedImage image;

	/**
	 * Constructor.
	 * 
	 * @param e
	 *            root edge
	 */
	ParseTree(final Edge e) {
		edge = e;
	}

	/**
	 * Creates a LaTeX document for this parse tree, with help from the Qtree
	 * package.
	 * 
	 * @return LaTeX document
	 */
	private String toLaTeX() {
		return "\\documentclass{article}\n\\usepackage{qtree}\n"
				+ "\\usepackage[utf8]{inputenc}\n\n"
				+ "\\usepackage[landscape]{geometry}\n"
				+ "\\usepackage{fullpage}\n"
				+ "\\pagestyle{empty}\n\n\\begin{document}\n\t\\Tree "
				+ edge.toLaTeX() + "\n\\end{document}\n";
	}

	/**
	 * Get the image of this parse tree.
	 * 
	 * @return parse tree image
	 * @throws IOException
	 *             if the conversion fails
	 */
	public synchronized BufferedImage getImage() throws IOException {
		if (image == null) {
			image = LaTeX.toImage(toLaTeX());
		}
		return image;
	}

}
