
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 14 18:48:19 CET 2012
//----------------------------------------------------

package de.woerteler.grammar;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int PAR_R = 3;
  public static final int NON_TERMINAL = 10;
  public static final int TO = 7;
  public static final int STAR = 5;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int PAR_L = 2;
  public static final int DOT = 9;
  public static final int TERMINAL = 11;
  public static final int error = 1;
  public static final int Q_MARK = 6;
  public static final int OR = 8;
}

